# Generated by Django 4.1.4 on 2022-12-22 14:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='for_user_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, size=4),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url1',
            field=models.URLField(default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.URLField(default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_name_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_size_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printing_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('size', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
