# Generated by Django 4.1.4 on 2022-12-31 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_accept_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_user_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, help_text='comma separated list: MB - member, CR - Core, JS - Joint Sec, GS - Gen Sec. Ex: GS,JS,CR', size=4),
        ),
    ]
