# Generated by Django 4.1.4 on 2023-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_for_user_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart_url',
            field=models.URLField(default=None, max_length=5000, null=True),
        ),
    ]
