# Generated by Django 4.1.4 on 2023-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image_url1_alter_product_image_url2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_image_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
