# Generated by Django 4.2.11 on 2024-08-17 19:40

from django.db import migrations
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=order.models.ThreeCharAutoField(editable=False, max_length=3, primary_key=True, serialize=False),
        ),
    ]
