# Generated by Django 4.1.4 on 2022-12-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_products_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cf_order_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
