# Generated by Django 4.1.4 on 2022-12-31 09:40

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cf_order_id_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cf_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_session_id',
        ),
        migrations.AddField(
            model_name='order',
            name='screenshot',
            field=models.ImageField(default=None, null=True, upload_to=order.models.screenshot_file_path),
        ),
    ]
