# Generated by Django 4.1.4 on 2023-01-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_cart_restored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_restored',
            new_name='mail_added',
        ),
        migrations.CreateModel(
            name='PendingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
