# Generated by Django 4.1.4 on 2023-01-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image_url1_alter_product_image_url2_and_more'),
        ('order', '0006_rename_cart_restored_order_mail_added_pendingemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product'),
        ),
    ]
